# Generated by Django 4.1.3 on 2022-12-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='appointment_slot_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
