# Generated by Django 4.1.3 on 2022-12-06 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_doctor_appointment_slot_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
