# Generated by Django 4.1.3 on 2022-12-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashbaord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_email', models.CharField(max_length=100)),
                ('patient_contact', models.CharField(max_length=12)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.CharField(max_length=20)),
                ('appointment_status', models.CharField(default='Open', max_length=10)),
            ],
        ),
    ]
