# Generated by Django 4.1.3 on 2022-12-07 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashbaord', '0002_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
