# Generated by Django 4.1.3 on 2022-12-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashbaord", "0004_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
